# HTML

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'sukoneck docker hub connection'
    repository: 'sukoneck/staticsite'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'adobuildtest'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'